daemon:
  modules:
    - Xim
engine:
  global_hotkeys:
    S-Space:
      behavior:
        Toggle:
          - Hangul
          - Latin
      result: Consume
    Esc:
      behavior:
        Switch: Latin
      result: Bypass
  hangul:
    addons:
      dubeolsik:
        - TreatJongseongAsChoseong
